"use client";

import React, { useState } from "react";
import { Layout } from "@/components/layout/layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  Play, 
  Users, 
  Clock, 
  Star, 
  Brain, 
  Shield, 
  Calendar,
  Gamepad2,
  Target,
  Trophy
} from "lucide-react";
import Link from "next/link";
import { GameChatInterface } from "@/components/chat/game-chat-interface";

// Game configurations with system prompts
const gameConfigs = {
  "1": {
    id: "1",
    name: "AI Dungeon Master",
    description: "An AI-powered text-based RPG where the dungeon master adapts to your choices in real-time, creating infinite adventures.",
    longDescription: "Experience the ultimate in adaptive storytelling with our AI Dungeon Master. This revolutionary text-based RPG uses advanced AI to create unique narratives that respond to your every choice. Whether you're a seasoned adventurer or new to role-playing games, the AI adapts its storytelling style and difficulty to match your preferences.",
    category: "Adventure",
    creator: "0x1234...5678",
    creatorName: "GameDev Studios",
    players: 1250,
    rating: 4.8,
    totalRatings: 89,
    playTime: "30-60 min",
    difficulty: "Medium",
    tags: ["RPG", "Text-based", "Adaptive", "Story", "Fantasy"],
    price: 0,
    isLive: true,
    createdAt: "2024-01-15",
    lastUpdated: "2024-01-20",
    systemPrompt: `You are an AI Dungeon Master for a text-based RPG game. Your role is to:

1. Create immersive, adaptive stories that respond to player choices
2. Maintain consistent game world rules and logic
3. Provide rich descriptions of environments, characters, and events
4. Handle player actions appropriately (combat, exploration, dialogue, etc.)
5. Track player stats like health, inventory, and location
6. Generate challenging but fair encounters
7. Allow for creative player input while maintaining narrative coherence

Game mechanics:
- Player has health (starts at 100)
- Combat uses simple dice rolls for resolution
- Players can explore, fight, talk, use items, etc.
- Multiple story paths based on player decisions
- Rich fantasy setting with magic, monsters, and adventure

Always respond in character as the dungeon master, describing outcomes and presenting new choices.`,
    features: [
      "Infinite storylines generated by AI",
      "Adaptive difficulty based on player choices",
      "Rich character development system",
      "Multiple fantasy worlds to explore",
      "Save and continue adventures anytime"
    ],
    screenshots: [
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Adventure+Scene+1",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Character+Creation",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Battle+System"
    ],
    reviews: [
      {
        id: "1",
        user: "0x9876...5432",
        userName: "AdventureSeeker",
        rating: 5,
        comment: "Incredible storytelling! The AI creates such immersive narratives that I've been playing for hours.",
        date: "2024-01-18"
      },
      {
        id: "2",
        user: "0x5432...9876",
        userName: "RPGMaster",
        rating: 4,
        comment: "Great concept and execution. The AI adapts well to different play styles.",
        date: "2024-01-16"
      }
    ]
  },
  "2": {
    id: "2",
    name: "Neural Chess",
    description: "Play chess against an AI that learns and adapts to your playing style throughout the game.",
    longDescription: "Challenge yourself against an advanced AI chess opponent that analyzes your playing patterns and adapts its strategy accordingly. Perfect for players of all skill levels.",
    category: "Strategy",
    creator: "0x8765...4321",
    creatorName: "ChessAI Labs",
    players: 890,
    rating: 4.9,
    totalRatings: 67,
    playTime: "15-45 min",
    difficulty: "Hard",
    tags: ["Chess", "Strategy", "Learning", "Competitive"],
    price: 0.1,
    isLive: true,
    createdAt: "2024-01-10",
    lastUpdated: "2024-01-18",
    systemPrompt: `You are Neural Chess AI, an advanced chess engine that:

1. Plays chess at various difficulty levels
2. Learns and adapts to opponent's playing style
3. Provides strategic analysis and move explanations
4. Maintains proper chess notation and game state
5. Offers hints and learning opportunities for players

Game features:
- Standard chess rules and piece movement
- Multiple difficulty levels (Beginner to Grandmaster)
- Learning mode with move explanations
- Pattern recognition and style adaptation
- Opening preparation and endgame analysis

Respond to moves in standard chess notation (e.g., "e2e4", "Nf3", "O-O").
Track game state and provide appropriate responses.`,
    features: [
      "Adaptive AI that learns your style",
      "Multiple difficulty levels",
      "Learning mode with explanations",
      "Pattern recognition",
      "Strategic analysis"
    ],
    screenshots: [
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Chess+Board",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Move+Analysis",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Game+History"
    ],
    reviews: [
      {
        id: "1",
        user: "0x1111...2222",
        userName: "ChessMaster",
        rating: 5,
        comment: "Amazing AI that actually adapts to my playing style. Great for improving my game!",
        date: "2024-01-17"
      }
    ]
  },
  "3": {
    id: "3",
    name: "Story Weaver",
    description: "Collaborative storytelling with AI where you and the AI create stories together.",
    longDescription: "Join forces with an AI writing partner to create amazing stories. Take turns adding to the narrative, develop characters, and explore creative writing in new ways.",
    category: "Creative",
    creator: "0x9876...1234",
    creatorName: "Creative AI",
    players: 2100,
    rating: 4.7,
    totalRatings: 134,
    playTime: "20-40 min",
    difficulty: "Easy",
    tags: ["Creative", "Storytelling", "Collaborative", "Writing"],
    price: 0,
    isLive: true,
    createdAt: "2024-01-05",
    lastUpdated: "2024-01-19",
    systemPrompt: `You are Story Weaver, a collaborative storytelling AI that:

1. Creates engaging, creative stories with the player
2. Maintains narrative consistency and character development
3. Responds to player input by continuing the story
4. Offers creative suggestions while respecting player direction
5. Handles various genres and writing styles

Story mechanics:
- Take turns adding to the story
- Develop characters, plot, and setting collaboratively
- Support multiple genres (fantasy, sci-fi, mystery, romance, etc.)
- Encourage creative writing and imagination
- Provide constructive feedback and suggestions

Always continue the story based on the player's input while maintaining narrative flow.`,
    features: [
      "Collaborative storytelling",
      "Multiple genres supported",
      "Character development tools",
      "Creative writing assistance",
      "Story branching options"
    ],
    screenshots: [
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Story+Scene",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Character+Creation",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Plot+Development"
    ],
    reviews: [
      {
        id: "1",
        user: "0x3333...4444",
        userName: "StoryTeller",
        rating: 5,
        comment: "Fantastic for creative writing! The AI is incredibly helpful and inspiring.",
        date: "2024-01-16"
      }
    ]
  },
  "4": {
    id: "4",
    name: "Code Challenge Arena",
    description: "AI generates programming challenges that adapt to your skill level and coding style.",
    longDescription: "Improve your coding skills with personalized programming challenges. The AI analyzes your solutions and creates increasingly sophisticated problems tailored to your learning pace.",
    category: "Educational",
    creator: "0x5432...9876",
    creatorName: "CodeAI Academy",
    players: 756,
    rating: 4.6,
    totalRatings: 89,
    playTime: "10-30 min",
    difficulty: "Medium",
    tags: ["Programming", "Education", "Challenges", "Adaptive"],
    price: 0.05,
    isLive: false,
    createdAt: "2024-01-08",
    lastUpdated: "2024-01-17",
    systemPrompt: `You are Code Challenge Arena AI, an educational programming tutor that:

1. Creates coding challenges appropriate for the player's skill level
2. Provides clear problem descriptions and requirements
3. Analyzes submitted solutions for correctness and efficiency
4. Offers constructive feedback and optimization suggestions
5. Tracks progress and adjusts difficulty accordingly

Challenge types:
- Algorithm problems
- Data structure implementations
- System design questions
- Code optimization tasks
- Debugging exercises

Support multiple programming languages and provide example solutions when helpful.
Encourage learning while maintaining an engaging, gamified experience.`,
    features: [
      "Personalized difficulty scaling",
      "Multiple programming languages",
      "Detailed solution analysis",
      "Progress tracking",
      "Code optimization tips"
    ],
    screenshots: [
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Code+Challenge",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Solution+Analysis",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Progress+Dashboard"
    ],
    reviews: [
      {
        id: "1",
        user: "0x5555...6666",
        userName: "CodeLearner",
        rating: 4,
        comment: "Great for practicing coding skills. The challenges adapt well to my level.",
        date: "2024-01-15"
      }
    ]
  },
  "5": {
    id: "5",
    name: "Mystery Detective",
    description: "Solve AI-generated mysteries where clues and suspects are created based on your investigation style.",
    longDescription: "Become a master detective in procedurally generated mystery cases. The AI creates unique crimes, suspects, and clues that adapt based on your investigation approach.",
    category: "Puzzle",
    creator: "0x2468...1357",
    creatorName: "Mystery Games Inc",
    players: 1456,
    rating: 4.5,
    totalRatings: 112,
    playTime: "45-90 min",
    difficulty: "Medium",
    tags: ["Mystery", "Detective", "Puzzle", "Investigation"],
    price: 0.2,
    isLive: true,
    createdAt: "2024-01-12",
    lastUpdated: "2024-01-18",
    systemPrompt: `You are Mystery Detective AI, a master of crime scene investigation that:

1. Creates engaging mystery scenarios with multiple suspects and clues
2. Provides realistic detective work and investigation mechanics
3. Responds to player questions and investigation actions
4. Tracks evidence and maintains logical consistency
5. Offers hints when players get stuck without giving away solutions

Investigation mechanics:
- Examine crime scenes for clues
- Interview suspects and witnesses
- Analyze evidence and alibis
- Follow leads and red herrings
- Make accusations when ready

Create unique mysteries that adapt to the player's investigation style and provide satisfying conclusions.`,
    features: [
      "Procedurally generated mysteries",
      "Multiple investigation paths",
      "Realistic detective work",
      "Clue analysis system",
      "Replayable cases"
    ],
    screenshots: [
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Crime+Scene",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Suspect+Interview",
      "https://via.placeholder.com/600x400/1f2937/ffffff?text=Evidence+Board"
    ],
    reviews: [
      {
        id: "1",
        user: "0x7777...8888",
        userName: "DetectiveFan",
        rating: 5,
        comment: "Love the unique mysteries! Each case feels fresh and engaging.",
        date: "2024-01-14"
      }
    ]
  }
};

// Mock game data - get from configs
const mockGame = gameConfigs["1"];

export default function GameProfile({ params }: { params: { id: string } }) {
  const [isPlaying, setIsPlaying] = useState(false);
  const gameConfig = gameConfigs[params.id as keyof typeof gameConfigs];

  const handlePlayGame = () => {
    setIsPlaying(true);
  };

  const handleExitGame = () => {
    setIsPlaying(false);
  };

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case "Easy": return "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200";
      case "Medium": return "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200";
      case "Hard": return "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200";
      default: return "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200";
    }
  };

  if (!gameConfig) {
    return (
      <Layout>
        <div className="container mx-auto px-4 py-8">
          <div className="text-center">
            <h1 className="text-3xl font-bold mb-4">Game Not Found</h1>
            <p className="text-muted-foreground mb-6">The requested game could not be found.</p>
            <Button asChild>
              <Link href="/games">Browse All Games</Link>
            </Button>
          </div>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="container mx-auto px-4 py-8">
        {isPlaying ? (
          <GameChatInterface
            gameConfig={gameConfig}
            onExit={handleExitGame}
          />
        ) : (
          <>
            {/* Game Header */}
            <div className="mb-8">
              <div className="flex flex-col lg:flex-row gap-8 items-start">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-3 rounded-lg bg-primary/10">
                      <Gamepad2 className="h-8 w-8 text-primary" />
                    </div>
                    <div>
                      <h1 className="text-3xl font-bold">{gameConfig.name}</h1>
                      <div className="flex items-center gap-2 mt-1">
                        <Badge variant="secondary">{gameConfig.category}</Badge>
                        {gameConfig.isLive && (
                          <Badge className="bg-green-500 text-white">
                            <div className="w-2 h-2 bg-white rounded-full mr-2 animate-pulse" />
                            Live
                          </Badge>
                        )}
                        <Badge
                          className={getDifficultyColor(gameConfig.difficulty)}
                          variant="secondary"
                        >
                          {gameConfig.difficulty}
                        </Badge>
                      </div>
                    </div>
                  </div>

                  <p className="text-lg text-muted-foreground mb-6">
                    {gameConfig.description}
                  </p>
              
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                    <div className="flex items-center gap-2">
                      <Users className="h-5 w-5 text-muted-foreground" />
                      <div>
                        <p className="font-medium">{gameConfig.players}</p>
                        <p className="text-sm text-muted-foreground">Players</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Star className="h-5 w-5 text-yellow-500" />
                      <div>
                        <p className="font-medium">{gameConfig.rating}</p>
                        <p className="text-sm text-muted-foreground">Rating</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Clock className="h-5 w-5 text-muted-foreground" />
                      <div>
                        <p className="font-medium">{gameConfig.playTime}</p>
                        <p className="text-sm text-muted-foreground">Play Time</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Trophy className="h-5 w-5 text-muted-foreground" />
                      <div>
                        <p className="font-medium">{gameConfig.price === 0 ? "Free" : `$${gameConfig.price}`}</p>
                        <p className="text-sm text-muted-foreground">Price</p>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-4 mb-6">
                    <Avatar className="h-10 w-10">
                      <AvatarImage src={`https://api.dicebear.com/7.x/identicon/svg?seed=${gameConfig.creator}`} />
                      <AvatarFallback>{gameConfig.creatorName?.slice(0, 2)}</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-medium">{gameConfig.creatorName}</p>
                      <p className="text-sm text-muted-foreground">{gameConfig.creator}</p>
                    </div>
                  </div>

                  <div className="flex flex-wrap gap-2 mb-6">
                    {gameConfig.tags.map((tag, idx) => (
                      <Badge key={idx} variant="outline">
                        {tag}
                      </Badge>
                    ))}
                  </div>

                  <Button
                    size="lg"
                    onClick={handlePlayGame}
                    disabled={isPlaying}
                    className="w-full md:w-auto"
                  >
                    <Play className="h-5 w-5 mr-2" />
                    {isPlaying ? "Loading..." : gameConfig.price === 0 ? "Play Free" : `Play for $${gameConfig.price}`}
                  </Button>
            </div>

                {/* Game Preview/Screenshot */}
                <div className="lg:w-96">
                  <Card>
                    <CardContent className="p-0">
                      <img
                        src={gameConfig.screenshots[0]}
                        alt="Game preview"
                        className="w-full h-64 object-cover rounded-lg"
                      />
                    </CardContent>
                  </Card>
                </div>
              </div>
            </div>

            {/* Content Tabs */}
            <Tabs defaultValue="overview" className="space-y-6">
              <TabsList className="grid w-full grid-cols-4">
                <TabsTrigger value="overview">Overview</TabsTrigger>
                <TabsTrigger value="features">Features</TabsTrigger>
                <TabsTrigger value="reviews">Reviews</TabsTrigger>
                <TabsTrigger value="details">Details</TabsTrigger>
              </TabsList>

              <TabsContent value="overview" className="space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Brain className="h-5 w-5" />
                      About This Game
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground leading-relaxed">
                      {gameConfig.longDescription}
                    </p>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>Screenshots</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      {gameConfig.screenshots.map((screenshot, idx) => (
                        <img
                          key={idx}
                          src={screenshot}
                          alt={`Screenshot ${idx + 1}`}
                          className="w-full h-40 object-cover rounded-lg border"
                        />
                      ))}
                    </div>
                  </CardContent>
                </Card>
              </TabsContent>

              <TabsContent value="features" className="space-y-6">
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Target className="h-5 w-5" />
                      Game Features
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-3">
                      {gameConfig.features.map((feature, idx) => (
                        <li key={idx} className="flex items-start gap-3">
                          <div className="h-2 w-2 rounded-full bg-primary mt-2 flex-shrink-0" />
                          <span>{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              </TabsContent>

              <TabsContent value="reviews" className="space-y-6">
                <div className="flex items-center gap-4 mb-6">
                  <div className="flex items-center gap-2">
                    <Star className="h-6 w-6 text-yellow-500 fill-current" />
                    <span className="text-2xl font-bold">{gameConfig.rating}</span>
                  </div>
                  <div className="text-muted-foreground">
                    Based on {gameConfig.totalRatings} reviews
                  </div>
                </div>

                <div className="space-y-4">
                  {gameConfig.reviews.map((review) => (
                    <Card key={review.id}>
                      <CardContent className="pt-6">
                        <div className="flex items-start gap-4">
                          <Avatar>
                            <AvatarImage src={`https://api.dicebear.com/7.x/identicon/svg?seed=${review.user}`} />
                            <AvatarFallback>{review.userName?.slice(0, 2)}</AvatarFallback>
                          </Avatar>
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-2">
                              <span className="font-medium">{review.userName}</span>
                              <div className="flex">
                                {Array.from({ length: 5 }, (_, i) => (
                                  <Star
                                    key={i}
                                    className={`h-4 w-4 ${
                                      i < review.rating ? "text-yellow-500 fill-current" : "text-gray-300"
                                    }`}
                                  />
                                ))}
                              </div>
                              <span className="text-sm text-muted-foreground">
                                {new Date(review.date).toLocaleDateString()}
                              </span>
                            </div>
                            <p className="text-muted-foreground">{review.comment}</p>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </TabsContent>

              <TabsContent value="details" className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Calendar className="h-5 w-5" />
                        Timeline
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-3">
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Released</span>
                        <span>{new Date(gameConfig.createdAt).toLocaleDateString()}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Last Updated</span>
                        <span>{new Date(gameConfig.lastUpdated).toLocaleDateString()}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Status</span>
                        <Badge variant="secondary">Active</Badge>
                      </div>
                    </CardContent>
                  </Card>

                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Shield className="h-5 w-5" />
                        Trust & Safety
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-3">
                      <div className="flex items-center gap-2">
                        <div className="h-2 w-2 rounded-full bg-green-500" />
                        <span className="text-sm">Creator Verified</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="h-2 w-2 rounded-full bg-green-500" />
                        <span className="text-sm">Content Reviewed</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="h-2 w-2 rounded-full bg-green-500" />
                        <span className="text-sm">Regular Updates</span>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </TabsContent>
            </Tabs>

        {/* Related Games */}
        <div className="mt-12">
          <h2 className="text-2xl font-bold mb-6">More Games Like This</h2>
          <div className="text-center py-8">
            <p className="text-muted-foreground mb-4">
              Explore more AI-powered games in the marketplace
            </p>
            <Button asChild>
              <Link href="/games">Browse All Games</Link>
            </Button>
          </div>
        </div>
      </div>
    </Layout>
  );
}
